var alphabet = "abcdefghijklmnopqrstuvwxyz";

levelDictionaries = {
	middlemaknh : {
		'lvl1' : 'lnsrtoheia',
		'lvl2' : 'wpyu',
		'lvl3' : 'dgjf',
		'lvl4' : 'cvm,',
		'lvl5' : 'bk',
		'lvl6' : 'q.',
		'lvl7' : alphabet,
	},
	middlemaknhkj : {
		'lvl1' : 'lnsrtoheia',
		'lvl2' : 'wpyu',
		'lvl3' : 'dgkf',
		'lvl4' : 'cvm,',
		'lvl5' : 'bj',
		'lvl6' : 'q.',
		'lvl7' : alphabet,
	},
	colemak : {
		'lvl1' : 'arstneio',
		'lvl2' : 'dh',
		'lvl3' : 'pgjl',
		'lvl4' : 'cvbk',
		'lvl5' : 'wfuy',
		'lvl6' : 'qzxm',
		'lvl7' : alphabet,
	},
	galliumpyf : {
		'lvl1' : 'qsdfjklm',
		'lvl2' : 'gh',
		'lvl3' : 'azer',
		'lvl4' : 'tycv',
		'lvl5' : 'uiop',
		'lvl6' : 'wxbn',
		'lvl7' : alphabet,
	},
	colemakdh : {
		'lvl1' : 'arstneio',
		'lvl2' : 'dh',
		'lvl3' : 'wfyu',
		'lvl4' : 'plgm',
		'lvl5' : 'bcvk',
		'lvl6' : 'qxjz',
		'lvl7' : alphabet,
	},
	qwerty : {
		'lvl1' : 'asdfer',
		'lvl2' : 'jkliuo',
		'lvl3' : 'ghty',
		'lvl4' : 'qwzx',
		'lvl5' : 'nmp',
		'lvl6' : 'cvb',
		'lvl7' : alphabet,
	},
	canary : {
		'lvl1' : 'crstneia',
		'lvl2' : 'dh',
		'lvl3' : 'lyuo',
		'lvl4' : 'pfgm',
		'lvl5' : 'bwkv',
		'lvl6' : 'jqzx',
		'lvl7' : alphabet,
	},
	custom : {
		'lvl1' : '',
		'lvl2' : '',
		'lvl3' : '',
		'lvl4' : '',
		'lvl5' : '',
		'lvl6' : '',
		'lvl7' : alphabet,
	},

}


var layoutMaps = {
	middlemaknh : {
		'Minus' : "[",
		'Equal' : "]",
		'KeyQ' : "q",
		'KeyW' : 'w',
		'KeyE' : 'l',
		'KeyR' : 'd',
		'KeyT' : 'g',
		'KeyY' : 'j',
		'KeyU' : 'f',
		'KeyI' : 'o',
		'KeyO' : 'u',
		'KeyP' : "'",
		'BracketLeft' : '/',
		'BracketRight' : '=',
		'Backslash' : '\\',
		'KeyA' : 'n',
		'KeyS' : 's',
		'KeyD' : 'r',
		'KeyF' : 't',
		'KeyG' : 'p',
		'KeyH' : 'y',
		'KeyJ' : 'h',
		'KeyK' : 'e',
		'KeyL' : 'i',
		'Semicolon' : 'a',
		'Quote' : '',
		'KeyZ' : 'z',
		'KeyX' : 'x',
		'KeyC' : 'c',
		'KeyV' : 'v',
		'KeyB' : 'b',
		'KeyN' : 'k',
		'KeyM' : 'm',
		'Comma' : ',',
		'Period' : '.',
		'Slash' : '/',
		'Backquote' : '`',
		'Digit1' : '1',
		'Digit2' : '2',
		'Digit3' : '3',
		'shiftLayer' : "default"
	},
	middlemaknhkj : {
		'Minus' : "[",
		'Equal' : "]",
		'KeyQ' : "q",
		'KeyW' : 'w',
		'KeyE' : 'l',
		'KeyR' : 'd',
		'KeyT' : 'g',
		'KeyY' : 'k',
		'KeyU' : 'f',
		'KeyI' : 'o',
		'KeyO' : 'u',
		'KeyP' : "'",
		'BracketLeft' : '/',
		'BracketRight' : '=',
		'Backslash' : '\\',
		'KeyA' : 'n',
		'KeyS' : 's',
		'KeyD' : 'r',
		'KeyF' : 't',
		'KeyG' : 'p',
		'KeyH' : 'y',
		'KeyJ' : 'h',
		'KeyK' : 'e',
		'KeyL' : 'i',
		'Semicolon' : 'a',
		'Quote' : '',
		'KeyZ' : 'z',
		'KeyX' : 'x',
		'KeyC' : 'c',
		'KeyV' : 'v',
		'KeyB' : 'b',
		'KeyN' : 'j',
		'KeyM' : 'm',
		'Comma' : ',',
		'Period' : '.',
		'Slash' : '/',
		'Backquote' : '`',
		'Digit1' : '1',
		'Digit2' : '2',
		'Digit3' : '3',
		'shiftLayer' : "default"
	},
	galliumpyf : {
		'Minus' : ")",
		'Equal' : "=",
		'KeyQ' : "b",
		'KeyW' : 'l',
		'KeyE' : 'd',
		'KeyR' : 'c',
		'KeyT' : 'v',
		'KeyY' : 'k',
		'KeyU' : 'f',
		'KeyI' : 'o',
		'KeyO' : 'u',
		'KeyP' : ',',
		'BracketLeft' : '^',
		'BracketRight' : '$',
		'Backslash' : '\\',
		'KeyA' : 'n',
		'KeyS' : 'r',
		'KeyD' : 't',
		'KeyF' : 's',
		'KeyG' : 'g',
		'KeyH' : 'y',
		'KeyJ' : 'h',
		'KeyK' : 'a',
		'KeyL' : 'e',
		'Semicolon' : 'i',
		'Quote' : "",
		'KeyZ' : 'q',
		'KeyX' : 'x',
		'KeyC' : 'm',
		'KeyV' : 'w',
		'KeyB' : 'j',
		'KeyN' : 'z',
		'KeyM' : 'p',
		'Comma' : "'",
		'Period' : ';',
		'Slash' : '.',
		'shiftLayer' : 'default',
	},
	colemak : {
		'Minus' : "-",
		'Equal' : "=",
		'KeyQ' : "q",
		'KeyW' : 'w',
		'KeyE' : 'f',
		'KeyR' : 'p',
		'KeyT' : 'g',
		'KeyY' : 'j',
		'KeyU' : 'l',
		'KeyI' : 'u',
		'KeyO' : 'y',
		'KeyP' : ';',
		'BracketLeft' : '[',
		'BracketRight' : ']',
		'Backslash' : '\\',
		'KeyA' : 'a',
		'KeyS' : 'r',
		'KeyD' : 's',
		'KeyF' : 't',
		'KeyG' : 'd',
		'KeyH' : 'h',
		'KeyJ' : 'n',
		'KeyK' : 'e',
		'KeyL' : 'i',
		'Semicolon' : 'o',
		'Quote' : "'",
		'KeyZ' : 'z',
		'KeyX' : 'x',
		'KeyC' : 'c',
		'KeyV' : 'v',
		'KeyB' : 'b',
		'KeyN' : 'k',
		'KeyM' : 'm',
		'Comma' : ',',
		'Period' : '.',
		'Slash' : '/',
		'shiftLayer' : 'default',
	}, 
	colemakdh : {
		'Minus' : "-",
		'Equal' : "=",
		'KeyQ' : "q",
		'KeyW' : 'w',
		'KeyE' : 'f',
		'KeyR' : 'p',
		'KeyT' : 'b',
		'KeyY' : 'j',
		'KeyU' : 'l',
		'KeyI' : 'u',
		'KeyO' : 'y',
		'KeyP' : ';',
		'BracketLeft' : '[',
		'BracketRight' : ']',
		'Backslash' : '\\',
		'KeyA' : 'a',
		'KeyS' : 'r',
		'KeyD' : 's',
		'KeyF' : 't',
		'KeyG' : 'g',
		'KeyH' : 'm',
		'KeyJ' : 'n',
		'KeyK' : 'e',
		'KeyL' : 'i',
		'Semicolon' : 'o',
		'Quote' : "'",
		'KeyZ' : 'x',
		'KeyX' : 'c',
		'KeyC' : 'd',
		'KeyV' : 'v',
		'KeyB' : 'z',
		'KeyN' : 'k',
		'KeyM' : 'h',
		'Comma' : ',',
		'Period' : '.',
		'Slash' : '/',
		'shiftLayer' : 'default',
	},
	qwerty : {
		'Minus' : "-",
		'Equal' : "=",
		'KeyQ' : "q",
		'KeyW' : 'w',
		'KeyE' : 'e',
		'KeyR' : 'r',
		'KeyT' : 't',
		'KeyY' : 'y',
		'KeyU' : 'u',
		'KeyI' : 'i',
		'KeyO' : 'o',
		'KeyP' : 'p',
		'BracketLeft' : '[',
		'BracketRight' : ']',
		'Backslash' : '\\',
		'KeyA' : 'a',
		'KeyS' : 's',
		'KeyD' : 'd',
		'KeyF' : 'f',
		'KeyG' : 'g',
		'KeyH' : 'h',
		'KeyJ' : 'j',
		'KeyK' : 'k',
		'KeyL' : 'l',
		'Semicolon' : ';',
		'Quote' : "'",
		'KeyZ' : 'z',
		'KeyX' : 'x',
		'KeyC' : 'c',
		'KeyV' : 'v',
		'KeyB' : 'b',
		'KeyN' : 'n',
		'KeyM' : 'm',
		'Comma' : ',',
		'Period' : '.',
		'Slash' : '/',
		'shiftLayer' : 'default',
	},
	canary : {
		'Minus' : "-",
		'Equal' : "=",
		'KeyQ' : "w",
		'KeyW' : 'l',
		'KeyE' : 'y',
		'KeyR' : 'p',
		'KeyT' : 'b',
		'KeyY' : 'z',
		'KeyU' : 'f',
		'KeyI' : 'o',
		'KeyO' : 'u',
		'KeyP' : ';',
		'BracketLeft' : '[',
		'BracketRight' : ']',
		'Backslash' : '\\',
		'KeyA' : 'c',
		'KeyS' : 'r',
		'KeyD' : 's',
		'KeyF' : 't',
		'KeyG' : 'g',
		'KeyH' : 'm',
		'KeyJ' : 'n',
		'KeyK' : 'e',
		'KeyL' : 'i',
		'Semicolon' : 'a',
		'Quote' : "'",
		'KeyZ' : 'j',
		'KeyX' : 'v',
		'KeyC' : 'd',
		'KeyV' : 'k',
		'KeyB' : 'q',
		'KeyN' : 'x',
		'KeyM' : 'h',
		'Comma' : '/',
		'Period' : ',',
		'Slash' : '.',
		'shiftLayer' : 'default',
	},
	custom : {
		'Minus' : " ",
		'Equal' : " ",
		'KeyQ' : " ",
		'KeyW' : ' ',
		'KeyE' : ' ',
		'KeyR' : ' ',
		'KeyT' : ' ',
		'KeyY' : ' ',
		'KeyU' : ' ',
		'KeyI' : ' ',
		'KeyO' : ' ',
		'KeyP' : ' ',
		'BracketLeft' : ' ',
		'BracketRight' : ' ',
		'Backslash' : ' ',
		'KeyA' : ' ',
		'KeyS' : ' ',
		'KeyD' : ' ',
		'KeyF' : ' ',
		'KeyG' : ' ',
		'KeyH' : ' ',
		'KeyJ' : ' ',
		'KeyK' : ' ',
		'KeyL' : ' ',
		'Semicolon' : ' ',
		'Quote' : " ",
		'KeyZ' : ' ',
		'KeyX' : ' ',
		'KeyC' : ' ',
		'KeyV' : ' ',
		'KeyB' : ' ',
		'KeyN' : ' ',
		'KeyM' : ' ',
		'Comma' : ' ',
		'Period' : ' ',
		'Slash' : ' ',
		'shiftLayer' : 'default',
	},
}
